language: c

before_install:
    - sudo apt-get -qq update
    - sudo apt-get -y install libssl-dev valgrind

install:
    - git clone https://github.com/creytiv/re.git
    - git clone https://github.com/creytiv/rem.git
    - cd re && make && sudo make install && cd ..
    - cd rem && make && sudo make install && cd ..
    - sudo ldconfig
    - wget "https://github.com/alfredh/pytools/raw/master/ccheck.py"

script: 
    - make EXTRA_CFLAGS=-Werror
    - valgrind --leak-check=full --error-exitcode=1 ./retest -r -v
    - python2 ccheck.py
